name: Terraform Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.4.0  # Use the version of Terraform you need

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
