name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Debug Azure Secrets
      run: |
        echo "CLIENT_ID: ${{ secrets.CLIENT_ID }}" # Do NOT print sensitive values in production
        echo "TENANT_ID: ${{ secrets.TENANT_ID }}" # Do NOT print sensitive values in production

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6  # Specify the Terraform version you want to use

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="variables.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="variables.tfvars"
